[package]
name = "ckb-resource"
version = "0.16.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
build = "build.rs"

[dependencies]
phf = "0.7.21"
includedir = "0.5.0"
tempfile = "3.0"
numext-fixed-hash = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
serde = "1.0"
serde_derive = "1.0"
# TODO: change this to stable published crate version once the system script PR
# is merged and published
ckb-system-scripts = { version = "0.2.0-alpha.2" }

[build-dependencies]
includedir_codegen = "0.5.0"
walkdir = "2.1.4"
ckb-system-scripts = { version = "0.2.0-alpha.2" }
numext-fixed-hash = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
