[package]
name = "ckb-traits"
version = "0.16.0-pre"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"

[dependencies]
ckb-core = { path = "../core" }
numext-fixed-hash = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
ckb-chain-spec = {path = "../spec"}
ckb-store = { path = "../store" }
ckb-script = { path = "../script" }
failure = "0.1.5"
